/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delano;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.time.Clock;
import java.util.TimerTask;
import javax.swing.JProgressBar;
import java.util.Timer;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;

/**
 *
 * @author 743537
 */
public class AulasDeJava extends javax.swing.JFrame {
    Timer ar;
    Timer felicidade;
    Timer fome;
    Timer ponto;
    int pontosNum;
    /**
     * Creates new form AulasDeJava
     */
    private Clock clock;
    public AulasDeJava() {
        initComponents();
        pontosNum = 0;
         ar = new Timer();
         ponto = new Timer();
         felicidade = new Timer();
         fome = new Timer();
        ar.schedule(new TimerTask() {
            @Override
            public void run() {
               progress.setValue(progress.getValue()-2);
               if(progress.getValue()<=0)
                {
                    morreu(5);
                }
            }
        }, 0, 100);
        ponto.schedule(new TimerTask() {
            @Override
            public void run() {
               score.setText("Score:"+pontosNum);
               pontosNum++;
            }
        }, 0, 100);
        felicidade.schedule(new TimerTask() {
            @Override
            public void run() {
               feliz.setValue(feliz.getValue()-1);
               if(feliz.getValue()<=0)
                {
                    morreu(3);
                }
             
            }
        }, 0, 500);

        fome.schedule(new TimerTask() {
            @Override
            public void run() {
               hungry.setValue(hungry.getValue()-8);
               if(hungry.getValue()<=0)
                {
                    morreu(4);
                }
            }
        }, 0, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress = new javax.swing.JProgressBar();
        respirar = new javax.swing.JButton();
        sexo = new javax.swing.JButton();
        comer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        feliz = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        hungry = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Life Simulator");
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        progress.setForeground(new java.awt.Color(12, 183, 240));
        progress.setMaximum(101);
        progress.setToolTipText("");
        progress.setValue(100);

        respirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delano/resources/icon-breath.png"))); // NOI18N
        respirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                respirarMouseClicked(evt);
            }
        });

        sexo.setText("( ͡͡ ° ͜ ʖ ͡ °)");
        sexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sexoMouseClicked(evt);
            }
        });

        comer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delano/resources/eat.png"))); // NOI18N
        comer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comerMouseClicked(evt);
            }
        });

        jLabel1.setText("Ar:");

        feliz.setForeground(new java.awt.Color(9, 206, 0));
        feliz.setMaximum(101);
        feliz.setToolTipText("");
        feliz.setValue(100);

        jLabel2.setText("Felicidade:");

        hungry.setBackground(new java.awt.Color(242, 240, 240));
        hungry.setForeground(new java.awt.Color(255, 0, 0));
        hungry.setMaximum(101);
        hungry.setToolTipText("");
        hungry.setValue(100);

        jLabel3.setText("Fome:");

        score.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(respirar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(feliz, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(hungry, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(score)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(respirar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hungry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feliz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void respirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respirarMouseClicked
        respirarFunc();
    }//GEN-LAST:event_respirarMouseClicked

    private void sexoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sexoMouseClicked
        sexoFunc();
    }//GEN-LAST:event_sexoMouseClicked
    private void morreu(int tipo)
    {
        ponto.cancel();
        ar.cancel();
        felicidade.cancel();
        fome.cancel();
        sexo.setEnabled(false);
        respirar.setEnabled(false);
        comer.setEnabled(false);
        feliz.setValue(0);
        progress.setValue(0);
        hungry.setValue(0);
        if(tipo==0)
        JOptionPane.showMessageDialog(this,
                            "Você morreu de AIDS.");
        if(tipo==1)
        JOptionPane.showMessageDialog(this,
                            "Você morreu de obesidade.");
        if(tipo==2)
        JOptionPane.showMessageDialog(this,
                            "Você morreu de hiperventilação.");
        if(tipo==3)
        JOptionPane.showMessageDialog(this,
                            "Você morreu de depressão.");
        if(tipo==4)
        JOptionPane.showMessageDialog(this,
                            "Você morreu de fome.");
        if(tipo==5)
        JOptionPane.showMessageDialog(this,
                            "Você morreu sufocado.");
        String nome = JOptionPane.showInputDialog("Qual o seu nome?", "Jogador");
        try(FileWriter fw = new FileWriter("rank", true);
        BufferedWriter bw = new BufferedWriter(fw);
        PrintWriter out = new PrintWriter(bw))
        {
            out.println(nome+":"+pontosNum);
            out.println("");
            //more code
            //more code
        } catch (Exception e) {
            e.printStackTrace();
            //exception handling left as an exercise for the reader
        }
    }
    void comerFunc()
    {
        if(comer.isEnabled())
            hungry.setValue(hungry.getValue()+5);
        if(hungry.getValue()>100)
        {
            morreu(1);
        }
    }
    void respirarFunc()
    {
        if(respirar.isEnabled())
            progress.setValue(progress.getValue()+10);
        if(progress.getValue()>100)
        {
            morreu(2);
        }
    }
    void sexoFunc()
    {
        if(sexo.isEnabled())
            feliz.setValue(feliz.getValue()+1);
        if(feliz.getValue()>100)
        {
            morreu(0);
        }
    }
    private void comerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comerMouseClicked
        comerFunc();
    }//GEN-LAST:event_comerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AulasDeJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AulasDeJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AulasDeJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AulasDeJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AulasDeJava().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comer;
    private javax.swing.JProgressBar feliz;
    private javax.swing.JProgressBar hungry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar progress;
    private javax.swing.JButton respirar;
    private javax.swing.JLabel score;
    private javax.swing.JButton sexo;
    // End of variables declaration//GEN-END:variables
}
